<?php
define('BASE_URL'   , SERVEUR_URL . APPLICATION_NAME);
define('BASE_FILE'  , WEB_REPOSITORY. APPLICATION_NAME);
define("SIMPLE_FRAMEWORK_BASE_REPOSITORY", BASE_FILE."SimpleFramework/");
define("SIMPLE_FRAMEWORK_APP_REPOSITORY", SIMPLE_FRAMEWORK_BASE_REPOSITORY."app/");
define("SIMPLE_FRAMEWORK_CONF_REPOSITORY", SIMPLE_FRAMEWORK_BASE_REPOSITORY."conf/");
define('APP_REPOSITORY'    , BASE_FILE . "app/");
define('LOG_REPOSITORY'    , SIMPLE_FRAMEWORK_BASE_REPOSITORY. "log/");
define("MODULES_REPOSITORY", SIMPLE_FRAMEWORK_APP_REPOSITORY. "modules/");
define('UI_REPOSITORY'     , SIMPLE_FRAMEWORK_APP_REPOSITORY. "ui/"); 
define('INDEX_REPOSITORY'  , SIMPLE_FRAMEWORK_APP_REPOSITORY. "Controller/");
define('SMARTY_LIB'        , BASE_FILE . "vendors/Smarty/Smarty.class.php");
?>
